In [1]:
import nashpy as nash
import numpy as np

In [2]:
A = np.array([[0,10,1],[10,0,1],[1,1,1]])
game = nash.Game(A)
game

Zero sum game with payoff matrices:

Row player:
[[ 0 10  1]
 [10  0  1]
 [ 1  1  1]]

Column player:
[[  0 -10  -1]
 [-10   0  -1]
 [ -1  -1  -1]]