### Task 1

In [1]:
import nashpy as nash
import numpy as np

In [4]:
A = np.array([[1,0,5],[0,3,0],[0,0,4]])
B = np.array([[1,0,0],[0,3,0],[5,0,4]])
game = nash.Game(A,B)
game

Bi matrix game with payoff matrices:

Row player:
[[1 0 5]
 [0 3 0]
 [0 0 4]]

Column player:
[[1 0 0]
 [0 3 0]
 [5 0 4]]

    Best responses for Row player:     1, 3, 5
    Best responses for Column player:  1, 3, 5
    it is immediate to find two Nash equilibria:

In [5]:
list(game.support_enumeration())

[(array([1., 0., 0.]), array([1., 0., 0.])),
 (array([0., 1., 0.]), array([0., 1., 0.])),
 (array([0.75, 0.25, 0.  ]), array([0.75, 0.25, 0.  ]))]

    Possibilities to achieve Nash equilibrium for the whole game with T=2:
    (r2,r2), (c2,c2)
    (r2,r1), (c2,c1)
    (r1,r2), (c1,c2)
    (r1,r1), (c1,c1)

As we can see players don't have the reason to change the tactic. Of course we can check cooperating and defect strategy but it's not gonna work. Anyway lets calculate all the equlibria. 

All possible summarized values of two choices should be built as matrixes 9x9:

In [8]:
A = np.array([
    [2, 1, 6, 1, 0, 5, 6, 5, 10], 
    [1, 4, 1, 0, 3, 0, 5, 8, 5], 
    [1, 1, 5, 0, 0, 4, 5, 5, 9],
    [1, 0, 5, 4, 3, 8, 1, 0, 5],
    [0, 3, 0, 3, 6, 3, 0, 3, 0],
    [0, 0, 4, 3, 3, 7, 0, 0, 4],
    [1, 0, 5, 1, 0, 5, 5, 4, 9],
    [0, 3, 0, 0, 3, 0, 4, 7, 4],
    [0, 0, 4, 0, 0, 4, 4, 4, 8]
])
B = np.array([
    [2, 1, 1, 1, 0, 0, 1, 0, 0], 
    [1, 4, 1, 0, 3, 0, 0, 3, 0], 
    [6, 1, 5, 5, 0, 4, 5, 0, 4], 
    [1, 0, 0, 4, 3, 3, 1, 0, 0], 
    [0, 3, 0, 4, 6, 3, 0, 3, 0], 
    [5, 0, 4, 8, 3, 7, 5, 0, 4], 
    [6, 5, 5, 1, 0, 0, 5, 4, 4], 
    [5, 8, 5, 0, 3, 0, 4, 7, 4], 
    [10, 5, 9, 5, 0, 4, 9, 4, 8]
])

In [9]:
game = nash.Game(A,B)
list(game.support_enumeration())

[(array([1., 0., 0., 0., 0., 0., 0., 0., 0.]),
  array([1., 0., 0., 0., 0., 0., 0., 0., 0.])),
 (array([0., 1., 0., 0., 0., 0., 0., 0., 0.]),
  array([0., 1., 0., 0., 0., 0., 0., 0., 0.])),
 (array([0., 0., 0., 1., 0., 0., 0., 0., 0.]),
  array([0., 0., 0., 1., 0., 0., 0., 0., 0.])),
 (array([0., 0., 0., 0., 1., 0., 0., 0., 0.]),
  array([0., 0., 0., 0., 1., 0., 0., 0., 0.])),
 (array([0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]),
  array([0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])),
 (array([0.75, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ]),
  array([0.75, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ])),
 (array([0.  , 0.75, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ]),
  array([0.  , 0.75, 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ])),
 (array([ 4.16333634e-17,  1.38777878e-17, -0.00000000e+00,  6.66666667e-01,
          3.33333333e-01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00]),
  array([ 0.  ,  0.  , -0.  ,  0.75,  0.25,  